#!/usr/bin/env python
import os
import serial
import time
import json
from sys import exit

os.system("sudo chmod -R 777 /dev/ttyTHS1")

connected = False
while not connected:
    try:
        arduino = serial.Serial(
            port = '/dev/ttyTHS1',
            baudrate = 115200,
            bytesize = serial.EIGHTBITS,
            parity = serial.PARITY_NONE,
            stopbits = serial.STOPBITS_ONE,
            timeout = 5,
            xonxoff = False,
            rtscts = False,
            dsrdtr = False,
            writeTimeout = 2
        )
        connected = True
    except KeyboardInterrupt:
        exit()
    except Exception as e:
        print(e)
        time.sleep(1)


data = ""
while True:
    try:
        char = arduino.read().decode()
        if char:
            data += char
        if char == '\n':
            print(data)
            data = ""

    except KeyboardInterrupt:
        exit()