#!/usr/bin/env python3
import serial
import time
import json
from sys import exit

connected = False
while not connected:
    try:
        arduino = serial.Serial(
            port = '/dev/ttyACM0',
            baudrate = 115200,
            bytesize = serial.EIGHTBITS,
            parity = serial.PARITY_NONE,
            stopbits = serial.STOPBITS_ONE,
            timeout = 0.01,
            xonxoff = False,
            rtscts = False,
            dsrdtr = False,
            writeTimeout = 2
        )
        connected = True
    except KeyboardInterrupt:
        exit()
    except Exception as e:
        print(e)
        time.sleep(1)


led_cmd = False

tx_rate = 1000
tx_cnt = 0

arduino.reset_input_buffer()
while True:
    if tx_cnt > tx_rate:
        # Transmit
        data = {"led": int(led_cmd)}
        data_str = json.dumps(data) + '\n'
        data_bytes = data_str.encode('utf-8')
        #print('Cmd:', data_bytes)
        arduino.write(data_bytes)
        led_cmd = not led_cmd

        tx_cnt = 0
    else:
        tx_cnt += 1



    # read
    #char = arduino.read().decode()
    data_available = arduino.in_waiting
    if data_available > 0:
        try:
            json_string = arduino.read(data_available).decode()
            rx_dict = json.loads(json_string)
            print('Encoders:', rx_dict["enc_feedback"], 'Step:', rx_dict["curr_step"], 'Speed:', rx_dict["curr_speed"], 'Err Sum', rx_dict["err_sum"])
        except: 
            print("Error!")
        
    #print(char)