#!/usr/bin/env python2

import rospy
import serial
import time
import json
import math
import os

from std_srvs.srv import Trigger, TriggerResponse

from marsha_msgs.msg import TeensyMsg
from marsha_msgs.srv import MoveCmd
from marsha_msgs.srv import JointCmd

from marsha_msgs.srv import PayloadCmd
from marsha_core.pcs_node import *

from control_msgs.srv import QueryTrajectoryState

# Contains command chmod -R 777 /dev/ttyTHS1
# https://askubuntu.com/questions/155791/how-do-i-sudo-a-command-in-a-script-without-being-asked-for-a-password
os.system("sudo /home/aaron/unlock_serial.sh")

def deg_to_rad(degree):
    return degree / 180 * math.pi



class Interface(PCSNode):

    def __init__(self):
        super(Interface, self).__init__("teensy_interface")

        self.led_cmd = False
        self.tx_rate = 2000
        self.tx_cnt = 0
        self.connected = False

        rospy.wait_for_service('joint_cmd')
        self.joint_cmd = rospy.ServiceProxy('joint_cmd', JointCmd)

        # Prevents Jerkiness
        # AR3: self.controller_state = rospy.ServiceProxy('/left/ar3/controllers/position/query_state', QueryTrajectoryState)
        print("waiting for service")
        rospy.wait_for_service('arm2d2/controllers/position/query_state')
        self.controller_state = rospy.ServiceProxy('arm2d2/controllers/position/query_state', QueryTrajectoryState)
        print("service found")

        rospy.Service('gripper/grasp_cmd', MoveCmd, self.graspCmdCallback)
        rospy.Service('gripper/is_grasped', Trigger, self.is_grasped_callback)

        rospy.Subscriber('teensy_cmd', TeensyMsg, self.teensyCmdCallback)
        self.enc_pub = rospy.Publisher('enc_feedback', TeensyMsg, queue_size=10)

        self.step_cmd = []
        self.fake_joint_pos = 0
        self.grasped = False
        self.grasp_time = 0

        # True represents closed
        self.gripper_state = "close"
        self.gripper_cmd = rospy.get_param('/gripper/hw/close')

        self.calibrating = False
        self.pcs_established = False

        rospy.loginfo("Connecting...")

        while not self.connected:
            try:
                self.arduino = serial.Serial(
                    port = '/dev/ttyACM0',
                    baudrate = 115200,
                    bytesize = serial.EIGHTBITS,
                    parity = serial.PARITY_NONE,
                    stopbits = serial.STOPBITS_ONE,
                    timeout = 10,
                    xonxoff = False,
                    rtscts = False,
                    dsrdtr = False,
                    writeTimeout = 2
                )
                self.connected = True
            except KeyboardInterrupt:
                exit()
            except Exception as e:
                print(e)
                time.sleep(1)

        rospy.loginfo("Connected!")

        #self.calibrate_callback(None)

    def is_grasped_callback(self, msg):
        res = TriggerResponse()
        res.success = self.grasped
        return res

    def graspCmdCallback(self, msg):
        rospy.loginfo('Gripper pose:' + str(msg.pose_name))
        self.gripper_state = msg.pose_name
        self.gripper_cmd = rospy.get_param('/gripper/hw/' + msg.pose_name)
        return True

    def calibrate_callback(self, msg):
        deg_per_steps = rospy.get_param('stepper_config/deg_per_step')
        limit_degs = rospy.get_param('stepper_config/limit_position')
        limit_steps = []
        

        if len(limit_degs) != len(deg_per_steps):
            raise Exception('Stepper Config does not contain the correct number of steppers')
        for i in range(len(limit_degs)-1):
            limit_steps.append(int(limit_degs[i] / deg_per_steps[i]))

        #print('limit_steps:' + str(limit_steps))
        data = {"steps": limit_steps}
        data_str = json.dumps(data) + '\n'
        rospy.loginfo("data" + data_str)
        data_bytes = data_str.encode('utf-8')

        limit_rads = [deg_to_rad(i) for i in limit_degs]
        self.step_cmd = limit_steps
        self.arduino.write(data_bytes)
        j_success = self.joint_cmd(limit_rads)
        print("j cmd success", j_success)
        self.calibrating = False
        rospy.loginfo("Steps:" + str(limit_steps))
        rospy.loginfo("Calibrating...")
        #limit_rads[1] = limit_rads[1] - 0.26
        #limit_rads[2] = limit_rads[2] + 0.087
        res = TriggerResponse()
        res.success = True
        return res


    def teensyCmdCallback(self, msg):
        cmd = list(msg.steps)
        #print('cmd:', cmd)
        self.fake_joint_pos = cmd[-1]
        cmd[-1] = self.gripper_cmd
        self.step_cmd = cmd
        #print('callback:', self.step_cmd)
        #print ('Command: ' +  str(self.step_cmd))



    def transmit_step(self):
        # Note: Moveit for some reason tries to move back to zero...
        # Checking if the controller acceleration == 0 is a really bad fix to the problem...
        state = self.controller_state(rospy.get_rostime())
        if state.acceleration[0] == 0.0:
            data = {"steps": self.step_cmd}
            #print("cmd:" + str(self.step_cmd))
            data_str = json.dumps(data) + '\n'
            data_bytes = data_str.encode('utf-8')

            self.arduino.write(data_bytes)
        #print("data", data_bytes)

    def transmit_led(self):
        data = {"led": int(self.led_cmd)}
        data_str = json.dumps(data) + '\n'
        data_bytes = data_str.encode('utf-8')
        #print('Cmd:', data_bytes)
        self.arduino.write(data_bytes)
        self.led_cmd = not self.led_cmd



    def run(self):
        self.arduino.reset_input_buffer()
        while not rospy.is_shutdown():
            if not self.calibrating:
                if self.tx_cnt > self.tx_rate:
                    self.transmit_step()
                    self.tx_cnt = 0
                else:
                    self.tx_cnt += 1



            # read
            #char = arduino.read().decode()
            data_available = self.arduino.in_waiting
            if data_available > 0:
                if self.calibrating:
                    self.calibrating = False
                    rospy.loginfo("Calibration Complete!")
                try:
                    json_string = self.arduino.read(data_available).decode()
                    print(json_string)
                    rx_dict = json.loads(json_string)
                    encoders = rx_dict["enc_feedback"]

                    if encoders[-1] > rospy.get_param('/gripper/hw/' + self.gripper_state) + 100:
                        self.grasped = True
                        if self.grasp_time == 0:
                            self.grasp_time = rospy.get_rostime()
                        else:
                            if (rospy.get_rostime() - self.grasp_time).to_sec() > 4:
                                self.gripper_cmd = encoders[-1]
                    else:
                        self.grasped = False
                        self.grasp_time = 0
                    
                    self.enc_pub.publish(encoders)
                    
                    print ('Encoders:  ' +  str(rx_dict["enc_feedback"]))
                    #print("Grip feedback", rx_dict["grip_desired"])
                            #' Step: ' +  str(rx_dict["curr_step"]) +
                            #' Speed: ' + str(rx_dict["curr_speed"]) +
                            #' Err Sum: ' + str(rx_dict["err_sum"]))
                except Exception as e:
                    print(e) 
                    # This issue is caused because the teensy interface is polling for data on the recieve line.
                    # This can be fixed by creating an interrupt to place any recieved data in a buffer.
                    # Currently it is not a large enough issue to spend the time doing this
                    rospy.logwarn("Teensy feedback rate is faster than the jetson can handle. Multiple transmissions recieved before Teensy Interface was ready.")
                    print("Recv: " + json_string)
                except KeyError:
                    rospy.logerr("Communicated with Teensy, but un-readable data received.")
                    self.pcs_cmd(PCSstate.ERROR1)
                if not self.pcs_established:
                    self.pcs_cmd(PCSstate.GOOD)
                    self.pcs_established = True
        

if __name__ == "__main__":
    #os.system("sudo chmod -R 777 /dev/ttyTHS1")
    interface = Interface()

    interface.run()