#!/usr/bin/env python

import rospy
import time

from std_msgs.msg import Empty

from std_srvs.srv import Trigger

from marsha_msgs.srv import ObjectObservation
from marsha_msgs.srv import PredictPosition
from marsha_msgs.srv import MoveCmd


def main():
    rospy.init_node('velocity_printer')
    rospy.wait_for_service('/observe_trajectory')
    observe_trajectory = rospy.ServiceProxy('/observe_trajectory', ObjectObservation)

    rospy.wait_for_service('prediction_ready')
    prediction_ready = rospy.ServiceProxy('prediction_ready', Trigger)

    rospy.wait_for_service('predict_position')
    predict_position = rospy.ServiceProxy('predict_position', PredictPosition)

    rospy.wait_for_service('/left/pose_cmd')
    pose_cmd = rospy.ServiceProxy('/left/pose_cmd', MoveCmd)

    rospy.wait_for_service('/left/gripper/grasp_cmd')
    grasp_cmd = rospy.ServiceProxy('/left/gripper/grasp_cmd', MoveCmd)

    reset_pub = rospy.Publisher("/reset", Empty, queue_size=1)

    poll_rate = rospy.Rate(75)

    reset_pub.publish()

    time.sleep(1)

    pose_cmd('prePickup')
    grasp_cmd('open')


    while not prediction_ready().success:
        print("Waiting for accurate detection...")
        #print("obs: " + str(observe_trajectory()))
        poll_rate.sleep()

    pose_cmd('preCatch')
    print(" ---- Observation Complete ---")
    observation = observe_trajectory()
    print(str(observation))

    prediction = predict_position(0.5)

    print("predicted position:\n" + str(prediction.position))

    time_until = prediction.predicted_time.data - rospy.get_rostime()

    print("Time until pass:" + str(time_until.to_sec()))

    rospy.sleep(time_until)

    pose_cmd('Catch')
    grasp_cmd('close')

    print('Done')

    

    # Remove once gripper is added
    #pose_cmd('preCatch')

    #time.sleep(1)

    #pose_cmd('prePickup')

    #time.sleep(2)

    #pose_cmd('pickup')

if __name__ == "__main__":
    main()