#!/usr/bin/env python

import rospy

from std_msgs.msg import Empty

from marsha_msgs.srv import MoveCmd

rospy.wait_for_service('/left/pose_cmd')
pose_cmd = rospy.ServiceProxy('/left/pose_cmd', MoveCmd)

rospy.wait_for_service('/left/async_pose_cmd')
async_pose_cmd = rospy.ServiceProxy('/left/async_pose_cmd', MoveCmd)

rospy.wait_for_service('/left/gripper/grasp_cmd')
grasp_cmd = rospy.ServiceProxy('/left/gripper/grasp_cmd', MoveCmd)

rospy.wait_for_service('/left/folding')
fold_cmd = rospy.ServiceProxy('/left/folding', MoveCmd)

reset_pub = rospy.Publisher('/reset', Empty, queue_size=5)

def throw():
    rospy.init_node('throw_controller')
    reset_pub.publish()

    fold_cmd('fold')
    pose_cmd("pre_handoff")
    async_pose_cmd("handoff")
    grasp_cmd("open")

if __name__ == "__main__":
    throw()