#!/bin/bash

cd /home/cyborg/catkin_ws/src/marsha

git add .

FILES=$(git status --porcelain | sed s/^...//);

git commit -a -m "Update Docs"

git checkout Auxiliary-Platform

for file in $FILES;
do
    git checkout main -- $file
done

git add .
git commit -a -m "Update Docs"


