#!/usr/bin/env python

import rospy
from std_msgs.msg import Int32

select_pub = rospy.Publisher('stepper_select', Int32, queue_size=10)
step_pub = rospy.Publisher('stepper_step', Int32, queue_size=10)

rospy.init_node('node_name')

while not rospy.is_shutdown():
    print("------------------------")
    stepper = input("Stepper: ")
    num_steps = input("Num steps: ")
    select_pub.publish(stepper)
    step_pub.publish(num_steps)