#!/usr/bin/env python

import rospy
from std_msgs.msg import Int32MultiArray
from time import sleep


step_pub = rospy.Publisher('stepper_step', Int32MultiArray, queue_size=10)

rospy.init_node('node_name')


"""
while not rospy.is_shutdown():
    print("------------------------")
    
    arr = Int32MultiArray(data=[16000, 0, 0, 0, 0, 0])

    step_pub.publish(arr)

    sleep(15)

    arr = Int32MultiArray(data=[-16000, 0, 0, 0, 0, 0])
    step_pub.publish(arr)
    sleep(15)
"""

while not rospy.is_shutdown():
    print("------------------------")

    deg = input("Enter desired angle:")

    steps = int(deg / 0.01125)
    
    arr = Int32MultiArray(data=[steps, 0, 0, 0, 0, 0])

    step_pub.publish(arr)

    sleep(1)



