#!/usr/bin/env bash
echo "Check Ros output with journalctl-u marsha"
source ~/catkin_ws/devel/setup.bash

ROS_MASTER_URI=http://jet:11311

ROS_HOSTNAME=marsha
echo "Launching..."
roslaunch arm2d2_hardware arm2d2.launch ns:=right
