#!/usr/bin/env bash
echo "Starting Mission..."

source ~/catkin_ws/devel/setup.bash

ROS_MASTER_URI=http://jet:11311

ROS_HOSTNAME=marsha
echo "Launching..."

roslaunch marsha_core right_mission.launch --wait
