left:
  num_joints: 6
  pose:
    handoff:
      position:
        x: -0.003
        y: 0.243
        z: 0.132
      orientation:
        x: 0.0215694
        y: 0.702411
        z: 0.00727993
        w: 0.711407

    pre_handoff:
      position:
        x: -0.003
        y: 0.243
        z: 0.132
      orientation:
        x: 0.00554178
        y: -0.000009
        z: -0.000007
        w: 0.99998

    straight:
      position:
        x: -0.00320445
        y: -0.00687238
        z: 0.377996
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1

  joints:
    straight:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    home:
      - -0.1909
      - 0.523599
      - 2.1435
      - 0
      - -1.0472

    folding:
      step_0:
        - -0.1909
        - -0.523599 # -pi/6
        - 2.1435
        - 0
        - 0.523599 # pi/6

      step_1:
        - 0.2
        - -1.5708 # -pi/2
        - 2.1435
        - 0
        - 1.5708 # pi/6

      step_2:
        - 0.2
        - -1.65806
        - 1.5708
        - 0
        - 2.0944

      step_3:
        - 0.3
        - -1.5708 # -pi/2
        - 0.0
        - 0.0
        - 1.5708



right:
  num_joints: 6
  pose:
    pre_handoff:
      position:
        x: 0.1401
        y: 0.243
        z: 0.132
      orientation:
        x: 0.00554178
        y: -0.000009
        z: -0.000007
        w: 0.99998

  joints:
    straight:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    home:
      - 0.1909
      - -0.523599
      - -2.1435
      - 0
      - 1.0472

    folding:
      step_0:
        - 0.1909
        - 0.523599 # -pi/6
        - -2.1435
        - 0
        - -0.523599 # pi/6

      step_1:
        - -0.2
        - 1.5708 # -pi/2
        - -2.1435
        - 0
        - -1.5708 # pi/6

      step_2:
        - -0.2
        - 1.65806
        - -1.5708
        - 0
        - -2.0944

      step_3:
        - -0.3
        - 1.5708 # -pi/2
        - 0.0
        - 0.0
        - -1.5708