left:
  num_joints: 6
  pose:
    post_throw:
      position:
        x: -0.003
        y: 0.23
        z: 0.132
      orientation:
        x: 0.0215694
        y: 0.702411
        z: 0.00727993
        w: 0.711407

    pre_throw:
      position:
        x: -0.1
        y: 0.2
        z: 0.132
      orientation:
        x: 0.0215694
        y: 0.702411
        z: 0.00727993
        w: 0.711407

    avoidance_1:
      position:
        x: 0
        y: 0.2
        z: 0.2
      orientation:
        x: 1
        y: 0
        z: 0
        w: 0

    avoidance_2:
      position:
        x: 0.22098
        y: 0.0346
        z: 0.199
      orientation:
        x: 0.7945
        y: 0
        z: 0.607
        w: 0

    avoidance_3:
      position:
        x: 0.189
        y: -0.179
        z: 0.208
      orientation:
        x: 0.794
        y: 0
        z: 0.607
        w: 0

    avoidance_4:
      position:
        x: -0.0476
        y: -0.249
        z: 0.1329
      orientation:
        x: 0.9343
        y: -0.0895
        z: -0.0327
        w: 0.3432



    straight:
      position:
        x: -0.00320445
        y: -0.00687238
        z: 0.377996
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1

  joints:
    straight:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    home:
      - 0
      - 0
      - 0
      - 0
      - 0

    home2:
      - -0.436332
      - 0.401426
      - 2.25147
      - -0.279253
      - -1.0821
      - 0.10472

    folding:
      step_0:
        - 0
        - -0.0698
        - -0.2268
        - 0
        - 0.2967


      step_1:
        - 0
        - 0.3491
        - -0.2618
        - 0
        - -1.13446

      step_2:
        - 0
        - 0.3491
        - -0.2618
        - -1.57
        - -1.256

      step_3:
        - 0
        - 0.3491
        - -0.34906
        - -1.57
        - 0.3491

      step_4:
        - -0.349
        - -0.610865
        - 0.43633
        - -1.57
        - 0.3491

      step_5:
        - -1.2217
        - -0.610865
        - 0.43633
        - -1.57
        - 0.3491

      step_6:
        - -1.2217
        - -1.9198
        - 0.61108
        - -1.57
        - 0.3491

      step_7:
        - -1.0472
        - -1.74533
        - -1.74533
        - -1.57
        - 0.524

      step_8:
        - -1.0472
        - -1.74533
        - -1.74533
        - -1.57
        - -1.222





right:
  num_joints: 6
  pose:
    catch:
      position:
        x: 0.27
        y: 0.2075
        z: 0.12
      orientation:
        x: 0.708137
        y: 0
        z: -0.706075
        w: 0

    pre_catch:
      position:
        x: 0.29
        y: 0.2
        z: 0.12
      orientation:
        x: 0.708137
        y: 0
        z: -0.706075
        w: 0

  joints:
    straight:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    home:
      - 0.401426
      - 0.191986
      - -2.14675
      - 0
      - -1.18682

    pre_ball_1:
      - 0.139626
      - -0.261799
      - -1.29154
      - 0
      - -1.58825

    pick_ball_1:
      - 0.139626
      - -0.314159
      - -1.5708
      - 0
      - -1.25664

    #home:
    #  - 0.1909
    #  - -0.523599
    #  - -2.1435
    #  - 0
    #  - 1.0472

    # Note: same as left but everything is negative
    folding:
      step_0:
        - 0
        - 0.0698
        - 0.2268
        - 0
        - -0.2967


      step_1:
        - 0
        - -0.3491
        - 0.2618
        - 0
        - 1.13446

      step_2:
        - 0
        - -0.3491
        - 0.2618
        - 1.57
        - 1.256

      step_3:
        - 0
        - -0.3491
        - 0.34906
        - 1.57
        - -0.3491

      step_4:
        - 0.349
        - 0.610865
        - -0.43633
        - 1.57
        - -0.3491

      step_5:
        - 1.2217
        - 0.610865
        - -0.349
        - 1.57
        - -0.3491

      step_6:
        - 1.3963
        - 1.9198
        - -0.61108
        - 1.57
        - -0.3491

      step_7:
        - 1.0472
        - 1.74533
        - 1.74533
        - 1.57
        - -0.524

      step_8:
        - 1.0472
        - 1.74533
        - 1.74533
        - 1.57
        - 1.222