
right:
  num_joints: 6
  pose:
    catch:
      position:
        x: 0.27
        y: 0.2075
        z: 0.12
      orientation:
        x: 0.708137
        y: 0
        z: -0.706075
        w: 0

    pre_catch:
      position:
        x: 0.29
        y: 0.2
        z: 0.12
      orientation:
        x: 0.708137
        y: 0
        z: -0.706075
        w: 0

  joints:
    straight:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    pre_home:
      - 0.0
      - 0.0
      - -0.054
      - 0.017
      - -0.079


    home:
      - 0
      - 0
      - 0
      - 0
      - 0

    pre_ball_1:
      - -0.006
      - 0.491
      - 0.091
      - 0.00
      - -0.199

    pick_ball_1:
      - -0.016
      - 0.435
      - 0.179
      - 0.0
      - -0.049

    pre_ball_2:
      - -0.297
      - 0.593
      - -0.227
      - 0
      - -0.367

    pick_ball_2:
      - -0.262
      - 0.541
      - -0.506
      - 0
      - -0.0349

    pre_throw:
      - -0.785
      - 1.92
      - 1.571
      - 1.571
      - 0.262

    throw:
      - 0.175
      - 1.92
      - 1.571
      - 1.571
      - -0.524

    pre_catch:
      - -0.785
      - 1.92
      - 1.571
      - 1.571
      - -0.524

    catch:
      - 0.175
      - 1.92
      - 1.571
      - 1.571
      - -0.524

    # Note: same as left but everything is negative
    folding:
      step_0:
        - -0.001
        - 0.196
        - -0.060
        - 0.0
        - -0.269

      step_1:
        - 0.006 #0.053
        - 0.441 #0.622
        - -0.01 #0.089
        - 0.0
        - -0.316 #-0.466

      step_2:
        - 0.012
        - 0.874
        - 0.227
        - 0.0
        - 0.649


      step_3:
        - 0.033
        - 1.676
        - 0.233
        - 0.0
        - -0.3


      step_4:
        - -0.017
        - 1.769
        - 0.0519
        - 0
        - -0.5

      step_5:
        - 0.017
        - 1.769
        - -0.5
        - 0
        - -0.127


