left:
  num_joints: 6
  pose:
    post_throw:
      position:
        x: -0.003
        y: 0.23
        z: 0.132
      orientation:
        x: 0.0215694
        y: 0.702411
        z: 0.00727993
        w: 0.711407

    pre_throw:
      position:
        x: -0.1
        y: 0.2
        z: 0.132
      orientation:
        x: 0.0215694
        y: 0.702411
        z: 0.00727993
        w: 0.711407

    avoidance_1:
      position:
        x: 0
        y: 0.2
        z: 0.2
      orientation:
        x: 1
        y: 0
        z: 0
        w: 0

    avoidance_2:
      position:
        x: 0.22098
        y: 0.0346
        z: 0.199
      orientation:
        x: 0.7945
        y: 0
        z: 0.607
        w: 0

    avoidance_3:
      position:
        x: 0.189
        y: -0.179
        z: 0.208
      orientation:
        x: 0.794
        y: 0
        z: 0.607
        w: 0

    avoidance_4:
      position:
        x: -0.0476
        y: -0.249
        z: 0.1329
      orientation:
        x: 0.9343
        y: -0.0895
        z: -0.0327
        w: 0.3432



    straight:
      position:
        x: -0.00320445
        y: -0.00687238
        z: 0.377996
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1

  joints:
    straight:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    home:
      - 0
      - 0
      - 0
      - 0
      - 0

    pre_ball_1:
      - -0.349
      - -0.349
      - 0.017
      - -0.035
      - 0.349

    pick_ball_1:
      - -0.332
      - -0.279
      - 0.297
      - -0.052
      - 0

    pre_ball_2:
      - 0.297
      - -0.593
      - 0.227
      - 0
      - 0.367

    pick_ball_2:
      - 0.262
      - -0.541
      - 0.506
      - -0.035
      - 0.0349

    pre_throw:
      - 0.785
      - -1.92
      - -1.571
      - -1.571
      - 0.524

    throw:
      - -0.175
      - -1.92
      - -1.571
      - -1.571
      - 0.524

    pre_catch:
      - 0.785
      - -1.92
      - -1.571
      - -1.571
      - 0.524

    catch:
      - -0.175
      - -1.92
      - -1.571
      - -1.571
      - 0.524


    folding:
      step_0:
        - 0
        - -0.2
        - -0.244
        - 0
        - 0.4


      step_1:
        - 0
        - -0.785
        - 0.349
        - 0
        - -0.559

      step_2:
        - 0
        - -1.75
        - 0.524
        - 0
        - -0.262

      step_3:
        - 0
        - -1.919
        - 0
        - 0
        - 0.785

      step_4:
        - 0
        - -1.919
        - -1.57
        - 0
        - 0.785

      step_5:
        - 0
        - -1.919
        - -1.57
        - 0
        - -1.222






right:
  num_joints: 6
  pose:
    catch:
      position:
        x: 0.27
        y: 0.2075
        z: 0.12
      orientation:
        x: 0.708137
        y: 0
        z: -0.706075
        w: 0

    pre_catch:
      position:
        x: 0.29
        y: 0.2
        z: 0.12
      orientation:
        x: 0.708137
        y: 0
        z: -0.706075
        w: 0

  joints:
    straight:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    home:
      - 0
      - 0
      - 0
      - 0
      - 0

    pre_ball_1:
      - 0.349
      - 0.349
      - -0.017
      - 0.035
      - -0.349

    pick_ball_1:
      - 0.332
      - 0.279
      - -0.297
      - 0.052
      - 0

    pre_ball_2:
      - -0.297
      - 0.593
      - -0.227
      - 0
      - -0.367

    pick_ball_2:
      - -0.262
      - 0.541
      - -0.506
      - 0
      - -0.0349

    pre_throw:
      - -0.785
      - 1.92
      - 1.571
      - 1.571
      - -0.524

    throw:
      - 0.175
      - 1.92
      - 1.571
      - 1.571
      - -0.524

    pre_catch:
      - -0.785
      - 1.92
      - 1.571
      - 1.571
      - -0.524

    catch:
      - 0.175
      - 1.92
      - 1.571
      - 1.571
      - -0.524

    # Note: same as left but everything is negative
    folding:
      step_0:
        - 0
        - 0.2
        - 0.244
        - 0
        - -0.4


      step_1:
        - 0
        - 0.785
        - -0.349
        - 0
        - 0.559

      step_2:
        - 0
        - 1.75
        - -0.524
        - 0
        - 0.262

      step_3:
        - 0
        - 1.919
        - 0
        - 0
        - -0.785

      step_4:
        - 0
        - 1.919
        - 1.57
        - 0
        - -0.785

      step_5:
        - 0
        - 1.919
        - 1.57
        - 0
        - 1.222