/left/arm2d2/controllers:
  state:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  position:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - gripper_joint

    constraints:
      goal_time: 0.1
      joint_1:
          trajectory: 0.2
          goal: 0.1
      joint_2:
          trajectory: 0.2
          goal: 0.1
      joint_3:
          trajectory: 0.2
          goal: 0.1
      joint_4:
          trajectory: 0.2
          goal: 0.1
      joint_5:
          trajectory: 0.2
          goal: 0.1
      gripper_joint:
          trajectory: 0.2
          goal: 0.1