#!/usr/bin/env python3

import gym

from stable_baselines3 import TD3

from marsha_ai.catch_bandit.gym_env import MarshaGym
from marsha_ai.catch_bandit.catch_interface import CatchInterface

def train():
    interface = CatchInterface()
    env = MarshaGym(interface)

    model = TD3("MlpPolicy", env, verbose=1)
    model.learn(total_timesteps=100)


if __name__ == "__main__":
    train()
    print("Done.")