#!/usr/bin/env python3

import gym
from stable_baselines3 import PPO
from marsha_ai.gym_env import MarshaGym
from marsha_ai.ros_interface import RosInterface

interface = RosInterface()
env = MarshaGym(interface)


model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()

try:
    for i in range(1000):
        # Note: Random reachable pose: moveGroupInterface::getRandomPose()
        action, _states = model.predict(obs, deterministic=True)
        obs, reward, done, info = env.step(action)
        if done:
            obs = env.reset()
except KeyboardInterrupt:
    rospy.loginfo('Exiting...')
except:
    rospy.logwarn('Exiting...')

env.close()


