#!/usr/bin/env python

import rospy
import smach

from marsha_ai.srv import MoveCmd

def command(pose_name):
    rospy.wait_for_service('pos_cmd')

    cmd = rospy.ServiceProxy('pos_cmd', MoveCmd)

    success = cmd(pose_name)
    return success

# define state Foo
class Pickup(smach.State):
    def __init__(self):
        smach.State.__init__(self, outcomes=['outcome1','outcome2'])
        self.counter = 0

    def execute(self, userdata):
        rospy.loginfo('Executing state Pickup')
        command("pickup")
        if self.counter < 3:
            self.counter += 1
            return 'outcome1'
        else:
            return 'outcome2'


# define state Bar
class Handoff(smach.State):
    def __init__(self):
        smach.State.__init__(self, outcomes=['outcome2'])

    def execute(self, userdata):
        rospy.loginfo('Executing state Handoff')
        command("handoff")
        return 'outcome2'
        



# main
def main():
    rospy.init_node('smach_example_state_machine')

    # Create a SMACH state machine
    sm = smach.StateMachine(outcomes=['outcome4', 'outcome5'])

    # Open the container
    with sm:
        # Add states to the container
        smach.StateMachine.add('Pickup', Pickup(), 
                               transitions={'outcome1':'Handoff', 
                                            'outcome2':'outcome4'})
        smach.StateMachine.add('Handoff', Handoff(), 
                               transitions={'outcome2':'Pickup'})

    # Execute SMACH plan
    outcome = sm.execute()


if __name__ == '__main__':
    main()