#!/usr/bin/env python

import rospy
from marsha_ai.msg import Pose
from marsha_ai.msg import Position
from marsha_ai.msg import Orientation

from tf.transformations import quaternion_from_euler

def main():
    rospy.init_node('Web_ros_interface', log_level=rospy.DEBUG)

    pos_pub = rospy.Publisher('pos_cmd', Pose, queue_size=10)
    rate = rospy.Rate(0.5)

    msg = Pose()
    pos = Position()
    pos.x = 0.27
    pos.y = -0.4
    pos.z = 0.3
    msg.pos = pos

    quaternion = quaternion_from_euler(1.5707, 0, -1.5707)

    orient = Orientation()
    orient.x = quaternion[0]
    orient.y = quaternion[1]
    orient.z = quaternion[2]
    orient.w = quaternion[3]
    msg.orient = orient


    i = 0
    while i < 4:
        pos_pub.publish(msg)
        rospy.logdebug("Sending message")
        rate.sleep()
        i += 1


if __name__ == "__main__":
    main()






