#!/usr/bin/env python

import rospy

from std_msgs.msg import Empty



def main():
    rospy.init_node('state_talker', log_level=rospy.DEBUG)

    pub = rospy.Publisher('get_state', Empty, queue_size=10)
    rate = rospy.Rate(1)

    while True:
        pub.publish(Empty())
        rospy.logdebug("Sending Empty Message")
        rate.sleep()



if __name__ == "__main__":
    main()






