#!/usr/bin/env python

import rospy
from marsha_ai.msg import Pose
from marsha_ai.msg import Position
from marsha_ai.msg import Orientation

def main():
    rospy.init_node('Web_ros_interface', log_level=rospy.DEBUG)

    pos_pub = rospy.Publisher('pos_cmd', Pose, queue_size=10)
    rate = rospy.Rate(0.5)

    msg = Pose()
    pos = Position()
    pos.x = 0.0
    pos.y = -0.4
    pos.z = 0.3
    msg.pos = pos
    orient = Orientation()
    orient.w = 0.5
    orient.x = -0.5
    orient.y = -0.5
    orient.z = 0.5
    msg.orient = orient


    i = 0
    while i < 20:
        pos_pub.publish(msg)
        rospy.logdebug("Sending message")
        rate.sleep()
        i += 1


if __name__ == "__main__":
    main()






