gripper:
  pose:
    open:
      0.7
    close:
      -0.5
    half:
      0.5
    half_closed:
      0.3

  hw:
    open:
      6300
    close:
      6200
    half_closed:
      1000
    grasp_mount:
      -1000
    
