joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

arm2d2/controllers/position:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5

  constraints:
    goal_time: 0.5
    joint_1:
        trajectory: 1
        goal: 0.5
    joint_2:
        trajectory: 1
        goal: 0.5
    joint_3:
        trajectory: 1
        goal: 0.5
    joint_4:
        trajectory: 1
        goal: 0.5
    joint_5:
        trajectory: 1
        goal: 0.5