joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: true
    max_acceleration: 50
    has_jerk_limits: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: true
    max_acceleration: 50
    has_jerk_limits: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: true
    max_acceleration: 50
    has_jerk_limits: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: true
    max_acceleration: 50
    has_jerk_limits: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: true
    max_acceleration: 50
    has_jerk_limits: false