#!/usr/bin/env python
import rospy
import tf

def main():
    rospy.init_node('grip_broadcast')
    ns = rospy.get_namespace()
    broadcaster = tf.TransformBroadcaster()
    rate = rospy.Rate(10.0)

    while not rospy.is_shutdown():
        broadcaster.sendTransform((0.0, 0.0, 0.0),
                                  (0.0, 0.0, 0.0, 1.0),
                                  rospy.Time.now(),
                                  "grip/world",
                                  "left/link_6")
        rate.sleep()

if __name__ == '__main__':
    main()