#!/usr/bin/env python

# This needs to be moved to the marsha_core package

import rospy


def grasp_planning():
    from marsha_msgs.srv import PlanGrasp
    from geometry_msgs.msg import Pose
    from std_msgs.msg import Time
    from std_msgs.msg import Float32

    rospy.init_node('test')
    ns = rospy.get_namespace()
    rospy.wait_for_service(ns + 'plan_grasp')
    plan_grasp = rospy.ServiceProxy(ns + 'plan_grasp', PlanGrasp)

    pre_grasp = Pose()
    pre_grasp.position.x = 0
    pre_grasp.position.y = 0.2
    pre_grasp.position.z = 0.1
    pre_grasp.orientation.x = 0
    pre_grasp.orientation.y = 0
    pre_grasp.orientation.z = 0
    pre_grasp.orientation.w = 1

    grasp = pre_grasp
    grasp.position.z = 0.2

    time_offset = Time(rospy.Time.now() + rospy.Duration(10))
    grasp_time = Float32(0.5)

    plan_grasp(pre_grasp, grasp, time_offset, grasp_time)


if __name__ == "__main__":
    grasp_planning()
