// Generated by gencpp from file ros_tcp_endpoint/RosUnityTopicList.msg
// DO NOT EDIT!


#ifndef ROS_TCP_ENDPOINT_MESSAGE_ROSUNITYTOPICLIST_H
#define ROS_TCP_ENDPOINT_MESSAGE_ROSUNITYTOPICLIST_H

#include <ros/service_traits.h>


#include <ros_tcp_endpoint/RosUnityTopicListRequest.h>
#include <ros_tcp_endpoint/RosUnityTopicListResponse.h>


namespace ros_tcp_endpoint
{

struct RosUnityTopicList
{

typedef RosUnityTopicListRequest Request;
typedef RosUnityTopicListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RosUnityTopicList
} // namespace ros_tcp_endpoint


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_tcp_endpoint::RosUnityTopicList > {
  static const char* value()
  {
    return "b0eef9a05d4e829092fc2f2c3c2aad3d";
  }

  static const char* value(const ::ros_tcp_endpoint::RosUnityTopicList&) { return value(); }
};

template<>
struct DataType< ::ros_tcp_endpoint::RosUnityTopicList > {
  static const char* value()
  {
    return "ros_tcp_endpoint/RosUnityTopicList";
  }

  static const char* value(const ::ros_tcp_endpoint::RosUnityTopicList&) { return value(); }
};


// service_traits::MD5Sum< ::ros_tcp_endpoint::RosUnityTopicListRequest> should match
// service_traits::MD5Sum< ::ros_tcp_endpoint::RosUnityTopicList >
template<>
struct MD5Sum< ::ros_tcp_endpoint::RosUnityTopicListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tcp_endpoint::RosUnityTopicList >::value();
  }
  static const char* value(const ::ros_tcp_endpoint::RosUnityTopicListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tcp_endpoint::RosUnityTopicListRequest> should match
// service_traits::DataType< ::ros_tcp_endpoint::RosUnityTopicList >
template<>
struct DataType< ::ros_tcp_endpoint::RosUnityTopicListRequest>
{
  static const char* value()
  {
    return DataType< ::ros_tcp_endpoint::RosUnityTopicList >::value();
  }
  static const char* value(const ::ros_tcp_endpoint::RosUnityTopicListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_tcp_endpoint::RosUnityTopicListResponse> should match
// service_traits::MD5Sum< ::ros_tcp_endpoint::RosUnityTopicList >
template<>
struct MD5Sum< ::ros_tcp_endpoint::RosUnityTopicListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tcp_endpoint::RosUnityTopicList >::value();
  }
  static const char* value(const ::ros_tcp_endpoint::RosUnityTopicListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tcp_endpoint::RosUnityTopicListResponse> should match
// service_traits::DataType< ::ros_tcp_endpoint::RosUnityTopicList >
template<>
struct DataType< ::ros_tcp_endpoint::RosUnityTopicListResponse>
{
  static const char* value()
  {
    return DataType< ::ros_tcp_endpoint::RosUnityTopicList >::value();
  }
  static const char* value(const ::ros_tcp_endpoint::RosUnityTopicListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TCP_ENDPOINT_MESSAGE_ROSUNITYTOPICLIST_H
