// Generated by gencpp from file marsha/TrainInfo.msg
// DO NOT EDIT!


#ifndef MARSHA_MESSAGE_TRAININFO_H
#define MARSHA_MESSAGE_TRAININFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marsha
{
template <class ContainerAllocator>
struct TrainInfo_
{
  typedef TrainInfo_<ContainerAllocator> Type;

  TrainInfo_()
    : loss(0.0)  {
    }
  TrainInfo_(const ContainerAllocator& _alloc)
    : loss(0.0)  {
  (void)_alloc;
    }



   typedef float _loss_type;
  _loss_type loss;





  typedef boost::shared_ptr< ::marsha::TrainInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marsha::TrainInfo_<ContainerAllocator> const> ConstPtr;

}; // struct TrainInfo_

typedef ::marsha::TrainInfo_<std::allocator<void> > TrainInfo;

typedef boost::shared_ptr< ::marsha::TrainInfo > TrainInfoPtr;
typedef boost::shared_ptr< ::marsha::TrainInfo const> TrainInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marsha::TrainInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marsha::TrainInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marsha::TrainInfo_<ContainerAllocator1> & lhs, const ::marsha::TrainInfo_<ContainerAllocator2> & rhs)
{
  return lhs.loss == rhs.loss;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marsha::TrainInfo_<ContainerAllocator1> & lhs, const ::marsha::TrainInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marsha

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marsha::TrainInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marsha::TrainInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marsha::TrainInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marsha::TrainInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marsha::TrainInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marsha::TrainInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marsha::TrainInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0243a756440bd40111a2b7951b9a568e";
  }

  static const char* value(const ::marsha::TrainInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0243a756440bd401ULL;
  static const uint64_t static_value2 = 0x11a2b7951b9a568eULL;
};

template<class ContainerAllocator>
struct DataType< ::marsha::TrainInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marsha/TrainInfo";
  }

  static const char* value(const ::marsha::TrainInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marsha::TrainInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 loss\n"
;
  }

  static const char* value(const ::marsha::TrainInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marsha::TrainInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.loss);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrainInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marsha::TrainInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marsha::TrainInfo_<ContainerAllocator>& v)
  {
    s << indent << "loss: ";
    Printer<float>::stream(s, indent + "  ", v.loss);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARSHA_MESSAGE_TRAININFO_H
