// Generated by gencpp from file marsha/TrainData.msg
// DO NOT EDIT!


#ifndef MARSHA_MESSAGE_TRAINDATA_H
#define MARSHA_MESSAGE_TRAINDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marsha
{
template <class ContainerAllocator>
struct TrainData_
{
  typedef TrainData_<ContainerAllocator> Type;

  TrainData_()
    : targets()  {
    }
  TrainData_(const ContainerAllocator& _alloc)
    : targets(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _targets_type;
  _targets_type targets;





  typedef boost::shared_ptr< ::marsha::TrainData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marsha::TrainData_<ContainerAllocator> const> ConstPtr;

}; // struct TrainData_

typedef ::marsha::TrainData_<std::allocator<void> > TrainData;

typedef boost::shared_ptr< ::marsha::TrainData > TrainDataPtr;
typedef boost::shared_ptr< ::marsha::TrainData const> TrainDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marsha::TrainData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marsha::TrainData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marsha::TrainData_<ContainerAllocator1> & lhs, const ::marsha::TrainData_<ContainerAllocator2> & rhs)
{
  return lhs.targets == rhs.targets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marsha::TrainData_<ContainerAllocator1> & lhs, const ::marsha::TrainData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marsha

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marsha::TrainData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marsha::TrainData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marsha::TrainData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marsha::TrainData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marsha::TrainData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marsha::TrainData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marsha::TrainData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa3cd371077e3b3151f9319b3ebdff23";
  }

  static const char* value(const ::marsha::TrainData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa3cd371077e3b31ULL;
  static const uint64_t static_value2 = 0x51f9319b3ebdff23ULL;
};

template<class ContainerAllocator>
struct DataType< ::marsha::TrainData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marsha/TrainData";
  }

  static const char* value(const ::marsha::TrainData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marsha::TrainData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] targets\n"
;
  }

  static const char* value(const ::marsha::TrainData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marsha::TrainData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrainData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marsha::TrainData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marsha::TrainData_<ContainerAllocator>& v)
  {
    s << indent << "targets[]" << std::endl;
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      s << indent << "  targets[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.targets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARSHA_MESSAGE_TRAINDATA_H
