# Parameters used for the kalman filter
detection_parameters:
  u_0: 1        # An initial estimate at how certain the measurement is. (Initial measurement should be good as the initial state is throwing arm end effector position)
  sigma_me: 0.00005288 #irl: 0.0007178 #gazebo: 0.00005288  # Position measurement error standard deviation (Determine with marsha_core:obj_measure)
  sigma_a: 0.001  # Random acceleration standard deviation
  
  # The difference between the average measured position and estimated position the is considered good enough to predict the future position and velocity
  # If the position has converged by this much, the estimated velocity which cannot be measured has converged this much
  # a higher value allows the arm to start moving sooner, but with less accurate aim
  sufficient_convergence: 0.07

  robot_base:
    x: 0.24
    y: 0
    z: 0


  acceleration:
    x: 0
    y: 0
    z: 0
