#!/usr/bin/env python

import rospy

from marsha_core.marsha_services.move_cmds import *


def main():
    rospy.init_node('avoidance')

    pose_cmd("avoidance_1")
    pose_cmd("avoidance_2")
    pose_cmd("avoidance_3")
    pose_cmd("avoidance_4")
    pose_cmd("avoidance_1")
    pose_cmd("avoidance_2")
    pose_cmd("avoidance_3")
    pose_cmd("avoidance_4")
    pose_cmd("avoidance_1")
    fold_cmd("home")

if __name__ == "__main__":
    main()