#!/usr/bin/env python

import rospy
import time
import sys

from marsha_msgs.srv import MoveCmd

ns = rospy.get_namespace()

print("waiting for services...")
print("ns:", ns)



rospy.wait_for_service(ns + 'joint_pose_cmd')
joint_cmd = rospy.ServiceProxy(ns + 'joint_pose_cmd', MoveCmd)

rospy.wait_for_service(ns + "gripper/grasp_cmd")
grasp_cmd = rospy.ServiceProxy(ns + "gripper/grasp_cmd", MoveCmd)

print("Services loaded!")
def unfold():
    print("unfolding...")
    joint_cmd("home")
    for i in range(0, 4):
        print(i)
        joint_cmd("folding/step_" + str(i))


def fold():
    print("folding...")
    grasp_cmd("close")
    for i in range(3, -1, -1):
        joint_cmd("folding/step_" + str(i))
    grasp_cmd("half")
    joint_cmd("home")
    grasp_cmd("close")

def home():
    print("Folding...")
    grasp_cmd("half")
    joint_cmd("home")
    grasp_cmd("close")

def demo():
    unfold()
    time.sleep(1)
    fold()

if __name__ == "__main__":
    rospy.init_node('unfold_cmd')
    print("starting...")

    if len(sys.argv) > 1:
        if sys.argv[1] == "unfold":
            unfold()

        elif sys.argv[1] == "home":
            home()

        elif sys.argv[1] == "fold":
            fold()
        else:
            demo()

    else:
        demo()