#!/usr/bin/env python

# Payload Control System

import rospy
import smach
import smach_ros

from marsha_core.pcs_node import PCSstate
from marsha_core.pcs_node import PCScmd
from marsha_core.payload_command_system import PCS_SM
from marsha_core.pcs_states import *




class Left_PCS(PCS_SM):
    def __init__(self):
        PCS_SM.__init__(self)

    def mission_sm(self):
        handshake = (self.get_handshake_status, self.reset_handshake)
        with self.sm:
            smach.StateMachine.add('Jetson_Comm_Check', Jetson_Comm_Check(self.connection_status),
                                transitions={'Success': 'Jetson_Sync_0', # usually Teensy comm check
                                             'Error': 'Mission_Fail'})

            smach.StateMachine.add('Jetson_Sync_0', Jetson_Sync(0, self.jet_comm, handshake),
                                transitions={'Ready': 'Wait_for_TE',
                                             'Timeout': 'Mission_Fail'})

            smach.StateMachine.add('Teensy_Comm_Check', Teensy_Comm_Check("teensy_interface", self.pcs_node_state, self.pcs_node_cmd),
                                transitions={'Success': 'Wait_for_TE',
                                             'Error': 'Mission_Fail'})

            smach.StateMachine.add('Wait_for_TE', Wait_for_TE("te_detector", self.pcs_node_state, self.pcs_node_cmd),
                                transitions={'Success': 'Mission_Success',
                                             'Error': 'Mission_Fail'})

            smach.StateMachine.add('Activate_Longeron_Cams', Activate_Longeron_Cams("longeron_cams", self.pcs_node_state, self.pcs_node_cmd),
                                transitions={'Success': 'Deactivate_Longeron_Cams',
                                             'Error': 'Mission_Fail'})

            smach.StateMachine.add('Deactivate_Longeron_Cams', Deactivate_Longeron_Cams("longeron_cams", self.pcs_node_state, self.pcs_node_cmd),
                                transitions={'Success': 'Mission_Success',
                                             'Error': 'Mission_Fail'})





if __name__ == "__main__":
    rospy.init_node("PCS")
    sm = Left_PCS()
    try:
        sm.run()
    except KeyboardInterrupt:
        pass