#!/usr/bin/env python

import rospy
import serial
import json

class SRobTelem():

    def __init__(self):
        rospy.init_node('srob_telemetry')

        print("Connecting...")

        try:
            self.srob = serial.Serial(
                port = '/dev/ttyUSB0',
                baudrate = 9600,
                bytesize = serial.EIGHTBITS,
                parity = serial.PARITY_NONE,
                stopbits = serial.STOPBITS_ONE,
                timeout = 10,
                xonxoff = False,
                rtscts = False,
                dsrdtr = False,
                writeTimeout = 2
            )
            self.connected = True
        except Exception as e:
            raise(e)

        print("Connected!")

    def run(self):

        while not rospy.is_shutdown():
            if self.srob.in_waiting > 0:
                json_string = self.srob.read_until('}').decode()
                    
                try:
                    rx_dict = json.loads(json_string)
                    print("Motor: " + str(rx_dict['Motor']) + " Fluid: " + str(rx_dict['Fluid']) + " Touch: " + str(rx_dict['Touch']))


                except ValueError:
                    rospy.logwarn("Recv: " + json_string)
            rospy.sleep(0.05)


if __name__ == "__main__":
    srobt = SRobTelem()
    srobt.run()

