#!/usr/bin/env python

import rospy
import serial

from marsha_msgs.srv import PayloadCmd
from marsha_core.pcs_node import *

class Telemetry(PCSNode):
    
    def __init__(self):
        super(Telemetry, self).__init__("telemetry")


        try:
            self.arduino = serial.Serial(
                port = '/dev/ttyACM0',
                baudrate = 115200,
                bytesize = serial.EIGHTBITS,
                parity = serial.PARITY_NONE,
                stopbits = serial.STOPBITS_ONE,
                timeout = 10,
                xonxoff = False,
                rtscts = False,
                dsrdtr = False,
                writeTimeout = 2
            )
            self.connected = True
        except Exception as e:
            raise(e)



