// Generated by gencpp from file ros_tcp_endpoint/RosUnityTopicListRequest.msg
// DO NOT EDIT!


#ifndef ROS_TCP_ENDPOINT_MESSAGE_ROSUNITYTOPICLISTREQUEST_H
#define ROS_TCP_ENDPOINT_MESSAGE_ROSUNITYTOPICLISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tcp_endpoint
{
template <class ContainerAllocator>
struct RosUnityTopicListRequest_
{
  typedef RosUnityTopicListRequest_<ContainerAllocator> Type;

  RosUnityTopicListRequest_()
    {
    }
  RosUnityTopicListRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RosUnityTopicListRequest_

typedef ::ros_tcp_endpoint::RosUnityTopicListRequest_<std::allocator<void> > RosUnityTopicListRequest;

typedef boost::shared_ptr< ::ros_tcp_endpoint::RosUnityTopicListRequest > RosUnityTopicListRequestPtr;
typedef boost::shared_ptr< ::ros_tcp_endpoint::RosUnityTopicListRequest const> RosUnityTopicListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ros_tcp_endpoint

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tcp_endpoint/RosUnityTopicListRequest";
  }

  static const char* value(const ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RosUnityTopicListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ros_tcp_endpoint::RosUnityTopicListRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TCP_ENDPOINT_MESSAGE_ROSUNITYTOPICLISTREQUEST_H
